### PR TITLE
Remove outdated GitHub injection script

### PR DESCRIPTION
**Pull request by kidonng**
- Remove outdated GitHub injection script since the new design is out
- ~~Remove `20px` icon size which is not consistent with GitHub's original size, people can easily change it via CSS~~
- Add build guide

### CODE REVIEW

**Comment by mallowigi** [comment]
Wait they removed the old design without any way to switch back? What a dick move...

**Comment by mallowigi** [comment]
About the width though, I really want this size to be the default one when installing the app. Maybe convert this via a css class ?

**Comment by kidonng** [comment]
I agree the `16px` GitHub use is a little small, I'm just concerning about the consistency with the filename's font size and compatibility with other extensions (like Refined GitHub).

It's fine for me if you don't feel like the size modification though.

**Comment by mallowigi** [comment]
I'll release a new version in a few weeks though, it's not that important. Perhaps I'll add more icons until then

**Pull request merged**
